version: '2'
services:
  jasmin:
    images: jookies/jasmin:latest
    restart: always
    volumes:
      - /var/log/jasmin:/var/log/jasmin
      - /etc/jasmin:/etc/jasmin
    ports:
      - "10.151.249.1:1401:1401"
      - "10.151.249.1:2775:2775"
      - "10.151.249.1:8990:8990"
  app:
    build: .
    command: "gunicorn"
    restart: always
    volumes:
      - ./JasminWebPanel:/app
      - ./config/local_settings.py:/app/main/local_settings.py
      - ./config/Makefile:/app/Makefile
      - ./config/wsgi.py:/app/main/wsgi.py
    ports:
      - "0.0.0.0:8000:8000"
